jobs:
  Build-And-Deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: "10"
          npm-version: "6"
          install-yarn: false
      - run: node --version
      - run: cd ../ && git clone -b fix-1432-circle-ci-1 https://github.com/raysonkoh/markbind.git
      - run: cd ../markbind/packages/cli && npm link
      - run: cd ../markbind && npm run setup
      - run: cd docs 
      - run: markbind build
      - run: markbind deploy --ci
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  Deploy-Markbind-Site:
    jobs:
      - Build-And-Deploy